name: editicert
description: Certificate Editor & Batch Exporter

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_adaptive_scaffold: ^0.1.4
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  collection: ^1.17.1
  transparent_pointer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true