name: editicert
description: Certificate Editor & Batch Exporter

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-174.3.beta <4.0.0"

dependencies:
  custom_mouse_cursor: ^1.1.0
  flex_color_picker: ^3.3.0
  flutter_rust_bridge: 2.0.0-dev.14
  rust_builder:
    path: rust_builder
  super_drag_and_drop: ^0.8.1
  touch_bar: ^0.3.0-alpha.1

dev_dependencies:
  collection: ^1.17.2
  dart_code_metrics_presets: ^2.5.0
  equatable: ^2.0.5
  ffigen: ^8.0.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  macos_window_utils: ^1.4.0
  melos: ^3.4.0
  signals: ^2.1.10
  transparent_pointer: ^1.0.0
  uuid: ^4.3.1
  vector_math: ^2.1.4
  very_good_analysis: ^5.1.0
  window_manager: ^0.3.7

flutter:
  uses-material-design: true

flutter_launcher_icons:
  #  android: "launcher_icon"
  #  ios: true
  #  image_path: "assets/icon/icon.png"
  #  min_sdk_android: 21 # android min sdk min:16, default 21
  #  web:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"
  #  windows:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon_1024.png"
