name: editicert
description: Certificate Editor & Batch Exporter

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_adaptive_scaffold: ^0.1.7+1
  collection: ^1.17.2
  transparent_pointer: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  window_manager: ^0.3.7
  macos_window_utils: ^1.4.0
  touch_bar: ^0.3.0-alpha.1
  get_it: ^7.6.4
  super_drag_and_drop: ^0.6.4
  custom_mouse_cursor: ^1.1.0
  flex_color_picker: ^3.3.0
  flutter_bloc: ^8.1.3
  vector_math: ^2.1.4
  equatable: ^2.0.5
  box_transform: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  dart_code_metrics_presets: ^2.5.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  #  android: "launcher_icon"
  #  ios: true
  #  image_path: "assets/icon/icon.png"
  #  min_sdk_android: 21 # android min sdk min:16, default 21
  #  web:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"
  #  windows:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon_1024.png"
