name: Flutter build

on:
  push:
    

jobs:
  dcm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Run DCM
        run: dcm analyze .
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: subosito/flutter-action@v2.11.0
        with:
          flutter-version: "3.18.0-0.2.pre"
          channel: "beta"
      - name: Get dependencies
        run: flutter pub get
      - name: Build macOS executable
        run: flutter build macos --release
      - name: Upload macOS executable
        uses: actions/upload-artifact@v3.1.3
        with:
          name: macos-executable
          path: build/macos/Build/Products/Release/*
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: subosito/flutter-action@v2.11.0
        with:
          flutter-version: "3.18.0-0.2.pre"
          channel: "beta"
      - name: Get dependencies
        run: flutter pub get
      - name: Build Windows executable
        run: flutter build windows --release
      - name: Upload Windows executable
        uses: actions/upload-artifact@v3.1.3
        with:
          name: windows-executable
          path: build/windows/runner/Release/*
